services:

  mosquitto:
    build: ./mosquitto       # uses the Dockerfile to use the volumes etc with correct rights and ownership
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    networks:
      - stack

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: stationuser
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: stations
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - stack
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-stationuser} -d ${POSTGRES_DB:-stations}"]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - stack

  # backend:
  #   Python + REST service goes here later.
  #   It will need to join the "stack" network so it can reach
  #   mosquitto:1883 and postgres:5432 by service name.

networks:
  stack:
    driver: bridge

volumes:
  mosquitto-data:
  mosquitto-log:
  postgres-data:
  grafana-data: